version: '2.0'
services:
    com_goutenoir_apps_travel-footprint-calculator:
        container_name: com_goutenoir_apps_travel-footprint-calculator
        restart: always
        build: .
        volumes:
        - .:/app

        # The server's nginx-reverse-proxy does not like ports.
        # Uncomment this to get it working on localhost for dev.
#        ports:
#        - "5000:5000"

        environment:
#            DEBUG: true
            # Config for server's nginx-reverse-proxy container
            LETSENCRYPT_HOST: travel-footprint-calculator.apps.goutenoir.com
            LETSENCRYPT_EMAIL: antoine@goutenoir.com
            VIRTUAL_HOST: travel-footprint-calculator.apps.goutenoir.com
            # 80 is the default port
            VIRTUAL_PORT: 80
            ###################################################


    com_goutenoir_apps_travel-footprint-calculator_mahcron:
        container_name: com_goutenoir_apps_travel-footprint-calculator_mahcron
        image: jsonfry/curl-cron
        environment:
#        - OPTIONS=localhost/compute
        - OPTIONS=travel-footprint-calculator.apps.goutenoir.com/compute
        - CRON_SCHEDULE="*/3 * * * *"

# Tip from https://github.com/jwilder/nginx-proxy/issues/1132#issuecomment-392460028
# Create it first: docker network create webproxy
networks:
    default:
       external:
          name: webproxy

